steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"
      - "--build-arg"
      - "PROJECT_ID=$PROJECT_ID"
      - "."
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"]
timeout: "900s" # 15 minutes
images:
  - gcr.io/$PROJECT_ID/$REPO_NAME:latest
