steps:
  - name: "gcr.io/kaniko-project/executor:v1.6.0"
    args:
      - --destination=gcr.io/$PROJECT_ID/firebase-emulator:latest
      - --cache=true
      - --dockerfile=Dockerfile
    env:
      - "PROJECT_ID=$PROJECT_ID"
