version: "3"
services:
  emulator:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      FIRESTORE_PROJECT_NAME: test
    ports:
      - 5001:5001
      - 9000:9000
      - 9090:9090 # firstore
      - 8085:8085
      # - 5000:5000
      - 4000:4000
    command: 'firebase emulators:start --only firestore,storage --project test'
    tty: true
    restart: unless-stopped